### ISSUE TITLE
Please make an mirror for which had died termux.net

### ISSUE THREAD

**Issue by yefeiyu** [termux/science-packages-21-bin#1]
such as this science-packages-21-bin So we can modified etc/apt/sourice.list and go on.

https://github.com/termux/termux-app/issues/2651

[Bug]: https://termux.net redirects to https://ipinfo.io/census #2651
 Closed
bidyut1153 opened this issue 8 days ago · 2 comments
 Closed
[Bug]: https://termux.net redirects to https://ipinfo.io/census
#2651
bidyut1153 opened this issue 8 days ago · 2 comments 
Labels
bug report
Comments

@bidyut1153 bidyut1153 commented 8 days ago •
edited 
Problem description

My android 5 (termux.net) redirects to ipinfo.io/census. Can you please change android5 repo

Steps to reproduce the behavior.

Go to termux.net
What is the expected behavior?

No response

System information

Chrome version: 98.0.4758.101
Operating system: Android

**Comment by RoninElliot** [comment]
i same problem
and all step in internet tested

install manual apt 

old version install

offline version install

update phone

termux-change-repro not found comment

change mirror download apt sources.list to deb https://packages.termux.org/apt/termux-main stable main and after enter apt update crash error code 1 libiconv.so unused DT

reinstall rom 

not working..

install new version: package not supprted [android 7.h| my android version 5.1.1] 
install old version : not working network unable to install 

before i rest factory my phone termux in my phone worked 

and noting for noting ..

HELP!

**Comment by Grimler91** [comment]
The repo at termux.net is ~5.5 GB, and github only allows repos of maximum 2 GB so it is not possible for us to upload it to github.

I have however uploaded the archive from https://archive.org/details/termux-repositories-legacy to packages.termux.org now. Can be accessed at https://packages.termux.org/termux-main-21/, to subscribe, put

```
deb https://packages.termux.org/termux-main-21 stable main
``` 

in `$PREFIX/etc/apt/sources.list`.

**Comment by parizxx** [comment]
Thx for update🙏🙏

**Comment by danicaStarR** [comment]
> The repo at termux.net is ~5.5 GB, and github only allows repos of maximum 2 GB so it is not possible for us to upload it to github.
> 
> I have however uploaded the archive from https://archive.org/details/termux-repositories-legacy to packages.termux.org now. Can be accessed at https://packages.termux.org/termux-main-21/, to subscribe, put
> 
> ```
> deb https://packages.termux.org/termux-main-21 stable main
> ```
> 
> in `$PREFIX/etc/apt/sources.list`.

@Grimler91 Can't work in Termux

![](https://user-images.githubusercontent.com/103302052/165932167-bbababcf-d36a-4e96-ac50-1f56ba30c28d.png)

**Comment by Grimler91** [comment]
Download and install latest termux-keyring package. See instructions in wiki: https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6.
